/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazes;

import javax.swing.WindowConstants;
import clases.ConexionBs;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class InCategorias extends javax.swing.JFrame {

    /**
     * Creates new form InCategorias
     */
    public InCategorias() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt tpidc = new TextPrompt("Categoria", tidca);
        TextPrompt tpnc = new TextPrompt("Numero", tnca);
        TextPrompt tpdc = new TextPrompt("Descripcion", tdecat);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de categorias por " +InicioSesion.usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnca = new javax.swing.JLabel();
        tnca = new javax.swing.JTextField();
        brcat = new javax.swing.JButton();
        titleicate = new javax.swing.JLabel();
        ldeca = new javax.swing.JLabel();
        tdecat = new javax.swing.JTextField();
        lidca = new javax.swing.JLabel();
        tidca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lnca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnca.setText("Numero");

        tnca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tnca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tncaActionPerformed(evt);
            }
        });

        brcat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brcat.setText("Registrar");
        brcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brcatActionPerformed(evt);
            }
        });

        titleicate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleicate.setText("Ingresar Categoria");

        ldeca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ldeca.setText("Descripcion:");

        tdecat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tdecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdecatActionPerformed(evt);
            }
        });

        lidca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lidca.setText("Nombre:");

        tidca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tidca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tdecat, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lidca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(lnca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ldeca)
                            .addComponent(tidca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(tnca))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(brcat)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(titleicate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleicate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lidca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ldeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tdecat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brcat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdecatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdecatActionPerformed

    private void tncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tncaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tncaActionPerformed

    private void brcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brcatActionPerformed
        String ncattt, nucatt, dectt;
        int valicam = 0;
        ncattt = tidca.getText().trim();
        nucatt = tnca.getText().trim();
        dectt = tdecat.getText().trim();
        if (ncattt.equals("")) {
            tidca.setBackground(Color.red);
            valicam++;
        }
        if (nucatt.equals("")) {
            tnca.setBackground(Color.red);
            valicam++;
        }
        if (dectt.equals("")) {
            tdecat.setBackground(Color.red);
            valicam++;
        }
        try {
            Connection cn2 = ConexionBs.conectarb();
            PreparedStatement pst2 = cn2.prepareStatement("select id_categoria from categoria where id_categoria = '" + ncattt + "'");
            ResultSet rs = pst2.executeQuery();
            if (rs.next()) {
                tidca.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Categoria ya existe");
                tidca.setBackground(Color.WHITE);
                tnca.setBackground(Color.WHITE);
                tdecat.setBackground(Color.WHITE);

                cn2.close();
            } else {
                cn2.close();
                if (valicam == 0) {
                    try {
                        Connection cn = ConexionBs.conectarb();
                        PreparedStatement pst = cn.prepareStatement(
                                "insert into categoria values(?,?,?)");

                        pst.setString(1, tidca.getText().trim());
                        pst.setString(2, tnca.getText().trim());
                        pst.setString(3, tdecat.getText().trim());

                        pst.executeUpdate();

                        tidca.setText("");
                        tnca.setText("");
                        tdecat.setText("");

                       JOptionPane.showMessageDialog(null, "Reistro exitoso");
                       this.dispose();

                    } catch (Exception e) {
                        System.out.println("Error en el boton registrar" + e);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
                    tidca.setBackground(Color.WHITE);
                    tnca.setBackground(Color.WHITE);
                    tdecat.setBackground(Color.WHITE);

                }
                cn2.close();
            }
        } catch (Exception e) {
                  System.out.println("Error en validar cateoria");
            JOptionPane.showMessageDialog(null, "Error al validar categoria, cantacte al administrador");
        }


    }//GEN-LAST:event_brcatActionPerformed

    private void tidcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brcat;
    private javax.swing.JLabel ldeca;
    private javax.swing.JLabel lidca;
    private javax.swing.JLabel lnca;
    private javax.swing.JTextField tdecat;
    private javax.swing.JTextField tidca;
    private javax.swing.JLabel titleicate;
    private javax.swing.JTextField tnca;
    // End of variables declaration//GEN-END:variables
}
