/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazes;

import java.sql.*;
import clases.ConexionBs;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class InicioSesion extends javax.swing.JFrame {

    public static String usuario = "";
    String contrase = "";

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Acceso al sistema");
        this.setResizable(false);
        TextPrompt tpc = new TextPrompt("           Nombre de usuario", Tusuario);
        TextPrompt tpco = new TextPrompt("               ***************", TCONTRA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lnusuario = new javax.swing.JLabel();
        INI = new javax.swing.JButton();
        Tusuario = new javax.swing.JTextField();
        TCONTRA = new javax.swing.JPasswordField();
        LCONTRA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Lnusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lnusuario.setText("Ingrese su nombre se usuario:");

        INI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        INI.setText("Iniciar sesion");
        INI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INIActionPerformed(evt);
            }
        });

        Tusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tusuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TCONTRA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TCONTRA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LCONTRA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LCONTRA.setText("Ingrese su contraseña:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema de ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(INI)
                    .addComponent(Tusuario)
                    .addComponent(TCONTRA)
                    .addComponent(LCONTRA, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lnusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lnusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LCONTRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(TCONTRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(INI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INIActionPerformed
        //MenuPrincipal menuprin = new MenuPrincipal();
        //menuprin.setVisible(true);
        //this.setVisible(false);
        usuario = Tusuario.getText().trim();
        contrase = TCONTRA.getText().trim();

        if (!usuario.equals("") || !contrase.equals("")) {
            try {
                Connection cn = ConexionBs.conectarb();
                // PreparedStatement pst = cn.prepareStatement(
                //         "select nombre from usuario where contraseña= ' " + contrase + "'");
                PreparedStatement pst = cn.prepareStatement("select nombre from usuario where contraseña = ?");
                pst.setString(1, contrase);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {

                    //int id = rs.getInt("id");
                    // String idd = String.valueOf(id);
                    // Tusuario.setText(idd);
                    String nuser = rs.getString("nombre");
                    cn.close();
                    Connection cn2 = ConexionBs.conectarb();
                    // PreparedStatement pst = cn.prepareStatement(
                    //         "select nombre from usuario where contraseña= ' " + contrase + "'");
                    PreparedStatement pst2 = cn2.prepareStatement("select contraseña from usuario where nombre = ?");
                    pst2.setString(1, usuario);
                    ResultSet rs2 = pst2.executeQuery();
                    if (rs2.next()) {
                        String npasww = rs2.getString("contraseña");
                        cn2.close();
                        
                        if(usuario.equals(nuser) && contrase.equals(npasww)){
                        dispose();

                        MenuPrincipal menuprin = new MenuPrincipal();
                        menuprin.setVisible(true);
                        menuprin.setTitle("Sistema ventas SME - Sesion " + usuario);
                       
                      
                        }else{
                         JOptionPane.showMessageDialog(null, "Nombre de usuario o contraseña incorrectos");
                    Tusuario.setText("");
                    TCONTRA.setText("");
                        }
                        
                    }else{
                     JOptionPane.showMessageDialog(null, "Nombre de usuario incorrecto");
                    Tusuario.setText("");
                    TCONTRA.setText("");
                    }
                    /*  if(){
                        dispose();
                         new MenuPrincipal().setVisible(true);
                    } */
                    //String passw = rs.getString("contraseña");

                    //menuprin.luser.setText("Bienvenido/a "+ nuser);         //forma decente
                    //String nuser = rs.getString("nombre");    forma simplificada
                    //new MenuPrincipal().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña de usuario incorrecta");
                    Tusuario.setText("");
                    TCONTRA.setText("");
                }
            } catch (Exception e) {
                System.err.println("Error en el boton iniciar sesion " + e);
                JOptionPane.showMessageDialog(null, "Error al iniciar sesion, contacte al personal administrativo");
                Tusuario.setText("");
                TCONTRA.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }
    }//GEN-LAST:event_INIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INI;
    private javax.swing.JLabel LCONTRA;
    private javax.swing.JLabel Lnusuario;
    private javax.swing.JPasswordField TCONTRA;
    private javax.swing.JTextField Tusuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
