/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazes;

/**
 *
 * @author ADMIN
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MNB = new javax.swing.JMenuBar();
        minicio = new javax.swing.JMenu();
        mitirinicio = new javax.swing.JMenuItem();
        musuarios = new javax.swing.JMenu();
        mitregistrarusuario = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mitvusuarios = new javax.swing.JMenuItem();
        mclientes = new javax.swing.JMenu();
        mitnuevocliente = new javax.swing.JMenuItem();
        mproveedores = new javax.swing.JMenu();
        mitnuevoproveedor = new javax.swing.JMenuItem();
        mproductos = new javax.swing.JMenu();
        mitnuevoproducto = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mitnuevacategoria = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mitrecat = new javax.swing.JMenuItem();
        mventas = new javax.swing.JMenu();
        mitnuevaventa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 100)); // NOI18N
        jLabel1.setText("S.M.E");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel2.setText("©2021 || SS S.A.L.F  M.A && E.A");

        MNB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MNB.setPreferredSize(new java.awt.Dimension(320, 23));

        minicio.setText("Inicio");
        minicio.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        mitirinicio.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitirinicio.setText("Ir al inicio");
        mitirinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitirinicioActionPerformed(evt);
            }
        });
        minicio.add(mitirinicio);

        MNB.add(minicio);

        musuarios.setText("Usuarios");
        musuarios.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        mitregistrarusuario.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitregistrarusuario.setText("Informacion de Usuarios");
        mitregistrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitregistrarusuarioActionPerformed(evt);
            }
        });
        musuarios.add(mitregistrarusuario);
        musuarios.add(jSeparator9);

        mitvusuarios.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitvusuarios.setText("Ver Usuarios");
        mitvusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitvusuariosActionPerformed(evt);
            }
        });
        musuarios.add(mitvusuarios);

        MNB.add(musuarios);

        mclientes.setText("Clientes");
        mclientes.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        mitnuevocliente.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitnuevocliente.setText("Control de clientes");
        mitnuevocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnuevoclienteActionPerformed(evt);
            }
        });
        mclientes.add(mitnuevocliente);

        MNB.add(mclientes);

        mproveedores.setText("Proveedores");
        mproveedores.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        mitnuevoproveedor.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitnuevoproveedor.setText("Proveedores asociados");
        mitnuevoproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnuevoproveedorActionPerformed(evt);
            }
        });
        mproveedores.add(mitnuevoproveedor);

        MNB.add(mproveedores);

        mproductos.setText("Productos");
        mproductos.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        mitnuevoproducto.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitnuevoproducto.setText("Administracion de productos");
        mitnuevoproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnuevoproductoActionPerformed(evt);
            }
        });
        mproductos.add(mitnuevoproducto);
        mproductos.add(jSeparator8);

        mitnuevacategoria.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitnuevacategoria.setText("Registro de categorias");
        mitnuevacategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnuevacategoriaActionPerformed(evt);
            }
        });
        mproductos.add(mitnuevacategoria);
        mproductos.add(jSeparator6);

        mitrecat.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitrecat.setText("Ver Informacion categorias");
        mitrecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitrecatActionPerformed(evt);
            }
        });
        mproductos.add(mitrecat);

        MNB.add(mproductos);

        mventas.setText("Ventas");
        mventas.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        mitnuevaventa.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        mitnuevaventa.setText("Facturacion y ventas");
        mitnuevaventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnuevaventaActionPerformed(evt);
            }
        });
        mventas.add(mitnuevaventa);

        MNB.add(mventas);

        setJMenuBar(MNB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitnuevoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnuevoclienteActionPerformed
        InCliente icliente = new InCliente();
        icliente.setVisible(true);
       // this.setVisible(false);
        
    }//GEN-LAST:event_mitnuevoclienteActionPerformed

    private void mitnuevoproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnuevoproveedorActionPerformed
        InProveedor iproveedor = new InProveedor();
        iproveedor.setVisible(true);
       // this.setVisible(false);
    }//GEN-LAST:event_mitnuevoproveedorActionPerformed

    private void mitnuevoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnuevoproductoActionPerformed
       InProducto iproducto = new InProducto();
       iproducto.setVisible(true);
      // this.setVisible(false);
    }//GEN-LAST:event_mitnuevoproductoActionPerformed

    private void mitirinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitirinicioActionPerformed
        InicioSesion isesion = new InicioSesion();
        isesion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mitirinicioActionPerformed

    private void mitregistrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitregistrarusuarioActionPerformed
        Loginn logi = new Loginn();
        logi.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_mitregistrarusuarioActionPerformed

    private void mitnuevacategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnuevacategoriaActionPerformed
     InCategorias icategorias = new InCategorias();
     icategorias.setVisible(true);
     //this.setVisible(false);
    }//GEN-LAST:event_mitnuevacategoriaActionPerformed

    private void mitvusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitvusuariosActionPerformed
        VRegistroUsuario vrusuarios = new VRegistroUsuario();
        vrusuarios.setVisible(true);
    }//GEN-LAST:event_mitvusuariosActionPerformed

    private void mitrecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitrecatActionPerformed
       VReistroCategoria vrecatt = new VReistroCategoria();
       vrecatt.setVisible(true);
    }//GEN-LAST:event_mitrecatActionPerformed

    private void mitnuevaventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnuevaventaActionPerformed
       InVentas iventa = new InVentas();
       iventa.setVisible(true);
    }//GEN-LAST:event_mitnuevaventaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MNB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu mclientes;
    private javax.swing.JMenu minicio;
    private javax.swing.JMenuItem mitirinicio;
    private javax.swing.JMenuItem mitnuevacategoria;
    private javax.swing.JMenuItem mitnuevaventa;
    private javax.swing.JMenuItem mitnuevocliente;
    private javax.swing.JMenuItem mitnuevoproducto;
    private javax.swing.JMenuItem mitnuevoproveedor;
    private javax.swing.JMenuItem mitrecat;
    private javax.swing.JMenuItem mitregistrarusuario;
    private javax.swing.JMenuItem mitvusuarios;
    private javax.swing.JMenu mproductos;
    private javax.swing.JMenu mproveedores;
    private javax.swing.JMenu musuarios;
    private javax.swing.JMenu mventas;
    // End of variables declaration//GEN-END:variables
}
